include: 
  - package:very_good_analysis/analysis_options.yaml
  - package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    prefer_final_fields: false
    prefer_final_locals: false
    sort_pub_dependencies: false
      - avoid_catches_without_on_clauses
    prefer_single_quotes: true
    require_trailing_commas: true

analyzer:
  errors:
    lines_longer_than_80_chars: warning
    unused_import: warning
    avoid_print: warning

  language:
    strict-inference: true
    strict-raw-types: true

  exclude:
    - 'lib/core/l10n/generated/intl/*.dart'
    - 'lib/core/utils/assets/assets.dart'
    - '**/generated/**'  # Exclude all files in a generated directory, if applicable
    - 'test'  # Exclude all files in a test directory
    - '**/*.g.dart'  # Exclude generated files to prevent dynamic errors