name: domain
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  freezed: ^3.0.3