// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_cqnUgqNuTdJewSkDhtVdd3Hdg7-0Kjc',
    appId: '1:295460515512:web:1888f0c624f24e1f5ace4d',
    messagingSenderId: '295460515512',
    projectId: 'maratha-shivmudra',
    authDomain: 'maratha-shivmudra.firebaseapp.com',
    storageBucket: 'maratha-shivmudra.firebasestorage.app',
    measurementId: 'G-9MSEF5GY6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgVSdzURCo5vuxl9KmhQJeufJ9K4nF8E',
    appId: '1:295460515512:android:70e0dca8c5b9e36d5ace4d',
    messagingSenderId: '295460515512',
    projectId: 'maratha-shivmudra',
    storageBucket: 'maratha-shivmudra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bzcNJsBNozmIIf4yYSOAFffW2Y0o-yU',
    appId: '1:295460515512:ios:626fd9baa560046e5ace4d',
    messagingSenderId: '295460515512',
    projectId: 'maratha-shivmudra',
    storageBucket: 'maratha-shivmudra.firebasestorage.app',
    iosBundleId: 'com.example.marathaShivmudra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1bzcNJsBNozmIIf4yYSOAFffW2Y0o-yU',
    appId: '1:295460515512:ios:626fd9baa560046e5ace4d',
    messagingSenderId: '295460515512',
    projectId: 'maratha-shivmudra',
    storageBucket: 'maratha-shivmudra.firebasestorage.app',
    iosBundleId: 'com.example.marathaShivmudra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_cqnUgqNuTdJewSkDhtVdd3Hdg7-0Kjc',
    appId: '1:295460515512:web:b39d8b208acd6ba85ace4d',
    messagingSenderId: '295460515512',
    projectId: 'maratha-shivmudra',
    authDomain: 'maratha-shivmudra.firebaseapp.com',
    storageBucket: 'maratha-shivmudra.firebasestorage.app',
    measurementId: 'G-QXH7WVMX98',
  );
}
