import 'package:flutter/material.dart';
import 'package:maratha_shivmudra/core/utils/extensions.dart';

abstract class StateConstant {
  static Map<String, Map<String, List<String>>> locationHierarchy(
      BuildContext context) {
    return {
      context.l10n.maharashtra: {
        context.l10n.ahilyanagar: [
          context.l10n.akole,
          context.l10n.jamkhed,
          context.l10n.karjat,
          context.l10n.kopargaon,
          context.l10n.nagar,
          context.l10n.nevasa,
          context.l10n.parner,
          context.l10n.pathardi,
          context.l10n.rahta,
          context.l10n.rahuri,
          context.l10n.sangamner,
          context.l10n.shevgaon,
          context.l10n.shrigonda,
          context.l10n.shrirampur,
        ],
        context.l10n.akola: [
          context.l10n.akola,
          context.l10n.akot,
          context.l10n.balapur,
          context.l10n.barshitakli,
          context.l10n.murtijapur,
          context.l10n.patur,
          context.l10n.telhara,
        ],
        context.l10n.amravati: [
          context.l10n.achalpur,
          context.l10n.amravati,
          context.l10n.anjangaon_surji,
          context.l10n.bhatkuli,
          context.l10n.chandur_railway,
          context.l10n.chandurbazar,
          context.l10n.chikhaldara,
          context.l10n.daryapur,
          context.l10n.dhamangaon_railway,
          context.l10n.dharni,
          context.l10n.morshi,
          context.l10n.nandgaon_khandeshwar,
          context.l10n.tiosa,
          context.l10n.warud,
        ],
        context.l10n.beed: [
          context.l10n.ambejogai,
          context.l10n.ashti,
          context.l10n.beed,
          context.l10n.dharur,
          context.l10n.georai,
          context.l10n.kaij,
          context.l10n.majalgaon,
          context.l10n.parli,
          context.l10n.patoda,
          context.l10n.shirur_kasar,
          context.l10n.wadwani,
        ],
        context.l10n.bhandara: [
          context.l10n.bhandara,
          context.l10n.lakhandur,
          context.l10n.lakhani,
          context.l10n.mohadi,
          context.l10n.pauni,
          context.l10n.sakoli,
          context.l10n.tumsar,
        ],
        context.l10n.buldhana: [
          context.l10n.buldana,
          context.l10n.chikhli,
          context.l10n.deolgaon_raja,
          context.l10n.jalgaon_jamod,
          context.l10n.khamgaon,
          context.l10n.lonar,
          context.l10n.malkapur,
          context.l10n.mehkar,
          context.l10n.motala,
          context.l10n.nandura,
          context.l10n.sangrampur,
          context.l10n.shegaon,
          context.l10n.sindkhed_raja,
        ],
        context.l10n.chandrapur: [
          context.l10n.ballarpur,
          context.l10n.bhadravati,
          context.l10n.brahmapuri,
          context.l10n.chandrapur,
          context.l10n.chimur,
          context.l10n.gondpipri,
          context.l10n.jiwati,
          context.l10n.korpana,
          context.l10n.mul,
          context.l10n.nagbhid,
          context.l10n.pombhurna,
          context.l10n.rajura,
          context.l10n.sawali,
          context.l10n.sindewahi,
          context.l10n.warora,
        ],
        context.l10n.chhatrapati_sambhajinagar: [],
        context.l10n.dharashiv: [],
        context.l10n.dhule: [],
        context.l10n.gadchiroli: [],
        context.l10n.gondia: [],
        context.l10n.hingoli: [],
        context.l10n.jalgaon: [],
        context.l10n.jalna: [],
        context.l10n.kolhapur: [],
        context.l10n.latur: [],
        context.l10n.mumbai: [],
        context.l10n.mumbai_suburban: [],
        context.l10n.nagpur: [],
        context.l10n.nanded: [],
        context.l10n.nandurbar: [],
        context.l10n.nashik: [],
        context.l10n.palghar: [],
        context.l10n.parbhani: [],
        context.l10n.pune: [],
        context.l10n.raigad: [],
        context.l10n.ratnagiri: [],
        context.l10n.sangli: [],
        context.l10n.satara: [],
        context.l10n.sindhudurg: [],
        context.l10n.solapur: [],
        context.l10n.thane: [],
        context.l10n.wardha: [],
        context.l10n.washim: [],
        context.l10n.yavatmal: [],
      },
    };
  }
}
